# Generated by Django 4.2.2 on 2023-07-12 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=100)),
                ('stop', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MetroBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=30)),
                ('stop', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('srStatus', models.CharField(default='Not Booked', max_length=30)),
                ('time', models.TimeField(null=True)),
                ('qr', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('add', models.CharField(max_length=100)),
                ('con', models.BigIntegerField()),
                ('psw', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mName', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StopsM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StopsW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=30)),
                ('stop', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('time', models.TimeField(null=True)),
                ('qr', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metroapp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amt', models.FloatField()),
                ('mBid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metroapp.metrobook')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metroapp.registration')),
                ('wBid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metroapp.waterbook')),
            ],
        ),
        migrations.AddField(
            model_name='metrobook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metroapp.registration'),
        ),
    ]
